"""add google form fields to student_lists

Revision ID: 7a25c4cbe398
Revises: 462aee7cf089
Create Date: 2026-04-05 17:24:01.434498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7a25c4cbe398'
down_revision: Union[str, None] = '462aee7cf089'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_journals_id'), table_name='student_journals')
    op.drop_index(op.f('ix_student_journals_profile_id'), table_name='student_journals')
    op.drop_table('student_journals')
    op.drop_index(op.f('ix_student_semester_gpas_id'), table_name='student_semester_gpas')
    op.drop_index(op.f('ix_student_semester_gpas_profile_id'), table_name='student_semester_gpas')
    op.drop_table('student_semester_gpas')
    op.drop_index(op.f('ix_students_id'), table_name='students')
    op.drop_index(op.f('ix_students_list_id'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_student_profiles_id'), table_name='student_profiles')
    op.drop_index(op.f('ix_student_profiles_student_id'), table_name='student_profiles')
    op.drop_table('student_profiles')
    op.drop_index(op.f('ix_student_conferences_id'), table_name='student_conferences')
    op.drop_index(op.f('ix_student_conferences_profile_id'), table_name='student_conferences')
    op.drop_table('student_conferences')
    op.drop_index(op.f('ix_student_patents_id'), table_name='student_patents')
    op.drop_index(op.f('ix_student_patents_profile_id'), table_name='student_patents')
    op.drop_table('student_patents')
    op.drop_table('staff_profiles')
    op.drop_index(op.f('ix_student_lists_id'), table_name='student_lists')
    op.drop_index(op.f('ix_student_lists_staff_id'), table_name='student_lists')
    op.drop_table('student_lists')
    op.drop_column('meetings', 'recall_bot_id')
    op.alter_column('staff', 'push_notifications_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('staff', 'email_notifications_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('staff', 'show_availability_to_others',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_constraint(op.f('staff_employee_id_key'), 'staff', type_='unique')
    op.create_index(op.f('ix_staff_employee_id'), 'staff', ['employee_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_staff_employee_id'), table_name='staff')
    op.create_unique_constraint(op.f('staff_employee_id_key'), 'staff', ['employee_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('staff', 'show_availability_to_others',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('staff', 'email_notifications_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('staff', 'push_notifications_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.add_column('meetings', sa.Column('recall_bot_id', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.create_table('student_lists',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('staff_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('token', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], name=op.f('student_lists_staff_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('student_lists_pkey')),
    sa.UniqueConstraint('token', name=op.f('student_lists_token_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_student_lists_staff_id'), 'student_lists', ['staff_id'], unique=False)
    op.create_index(op.f('ix_student_lists_id'), 'student_lists', ['id'], unique=False)
    op.create_table('staff_profiles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('staff_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('headline', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('about', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('linkedin_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('personal_website', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('achievements', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('education', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('experience', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], name=op.f('staff_profiles_staff_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('staff_profiles_pkey')),
    sa.UniqueConstraint('staff_id', name=op.f('staff_profiles_staff_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('student_patents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('application_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['student_profiles.id'], name=op.f('student_patents_profile_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('student_patents_pkey'))
    )
    op.create_index(op.f('ix_student_patents_profile_id'), 'student_patents', ['profile_id'], unique=False)
    op.create_index(op.f('ix_student_patents_id'), 'student_patents', ['id'], unique=False)
    op.create_table('student_conferences',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('conference_name', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('paper_title', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('attended_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['student_profiles.id'], name=op.f('student_conferences_profile_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('student_conferences_pkey'))
    )
    op.create_index(op.f('ix_student_conferences_profile_id'), 'student_conferences', ['profile_id'], unique=False)
    op.create_index(op.f('ix_student_conferences_id'), 'student_conferences', ['id'], unique=False)
    op.create_table('student_profiles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('overall_cgpa', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('submission_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_submitted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('student_profiles_student_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('student_profiles_pkey'))
    )
    op.create_index(op.f('ix_student_profiles_student_id'), 'student_profiles', ['student_id'], unique=True)
    op.create_index(op.f('ix_student_profiles_id'), 'student_profiles', ['id'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('list_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('student_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('register_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('missed_updates_this_month', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['list_id'], ['student_lists.id'], name=op.f('students_list_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('students_pkey')),
    sa.UniqueConstraint('list_id', 'register_number', name=op.f('uq_student_list_regnum'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_students_list_id'), 'students', ['list_id'], unique=False)
    op.create_index(op.f('ix_students_id'), 'students', ['id'], unique=False)
    op.create_table('student_semester_gpas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('semester_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('gpa', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['student_profiles.id'], name=op.f('student_semester_gpas_profile_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('student_semester_gpas_pkey')),
    sa.UniqueConstraint('profile_id', 'semester_number', name=op.f('uq_profile_semester'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_student_semester_gpas_profile_id'), 'student_semester_gpas', ['profile_id'], unique=False)
    op.create_index(op.f('ix_student_semester_gpas_id'), 'student_semester_gpas', ['id'], unique=False)
    op.create_table('student_journals',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('journal_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('publish_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['student_profiles.id'], name=op.f('student_journals_profile_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('student_journals_pkey'))
    )
    op.create_index(op.f('ix_student_journals_profile_id'), 'student_journals', ['profile_id'], unique=False)
    op.create_index(op.f('ix_student_journals_id'), 'student_journals', ['id'], unique=False)
    # ### end Alembic commands ###